#!/bin/bash
#PBS -l nodes=1:ppn=2,walltime=04:00:00
#PBS -N executable
#PBS -q short

module load gcc/4.9.2
module load shared
module load mvapich2/gcc/64/2.1
module load blas/gcc/64/3.5.0
module load torque/5.1.0

cd $PBS_O_WORKDIR

mpirun -np 2 ./executable 4 4 1 output_file
